# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa9ae485139863d0865c44a7fa96e6372fc547953560955153bae1951d3b18ca4cb5ee93f66b43f75758619c35a1b82f0eef359472a02f4a6edab09759f3b8d4

test:
  secret_key_base: 1175285f160315784782bbb9d91527f3c96136e4eb8c198540e9cba9371b8b8063d6c845710d9c300a3fd1091a82dba486063558e673b036d88076948b556e03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
